AllCops:
  NewCops: enable

  Exclude:
    - db/migrate/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - test/**/*
    - app/admin/**/*
    - app/channels/**/*
    - app/jobs/**/*
    - node_modules/**/*
    - Rakefile
    - config.ru

require:
  - rubocop-rails

Style/Encoding:
  Enabled: false

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

Layout/LineLength:
  Description: "Limit lines to 110 characters. (Default is 80)"
  Max: 110

Style/FrozenStringLiteralComment:
  Description: To help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: false

Style/WordArray:
  Description: "Use %w or %W for arrays of words."
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Lint/UnusedBlockArgument:
  AutoCorrect: false

Lint/UnusedMethodArgument:
  AutoCorrect: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - db/schema.rb
  Max: 100

Metrics/AbcSize:
  Enabled: false
